### ISSUE TITLE
Does it support gif image?

### ISSUE THREAD

**Issue by xeoshow** [hairyf/vue3-pixi#106]
Hello,

Nice to see your project, and found below demo which supports video, does it support gif image as well? Something like below. Thanks!
```
<sprite
    v-if="play"
    texture="https://pixijs.com/assets/funny.gif"
    :width="screen.width"
    :height="screen.height"
  />
```

video demo:
```
https://vue3-pixi.vercel.app/examples/sprite/video.html

<sprite
    v-if="play"
    texture="https://pixijs.com/assets/video.mp4"
    :width="screen.width"
    :height="screen.height"
  />
```

**Comment by xeoshow** [comment]
看了下作者，貌似都是中国人，哈哈就用中文啦。问了下GPT，有一个叫`@pixi/gif` 的库，不知是否可以直接整合进来？比序列帧更方便~

···
为了在 PixiJS 中播放 `.gif` 动画，你可以使用一个名为 `@pixi/gif` 的库。这个库可以处理 `.gif` 文件的播放，包含停止、循环、改变速度等。

你可以通过以下命令安装这个库：

```bash
npm install @pixi/gif
```

安装之后，你可以按照库的文档来使用它。这里是库的官方文档链接：[PixiJS GIF API Documentation](https://pixijs.io/gif/docs/)

以及这是该库的 npm 页面链接和 GitHub 仓库，提供了更多信息和源代码：[npm @pixi/gif](https://www.npmjs.com/package/@pixi/gif) 和 [github.com/q1998763/pixi-gif](https://github.com/q1998763/pixi-gif)

请确保查看文档并按照说明将库集成到你的 PixiJS 项目中。这样，你就可以继续使用 `.gif` 文件格式而无需将其转换为单独的帧图片。

**Comment by hairyf** [comment]
`<Assets />` or `<sprite />` can be directly supported by importing @ pixi/gif

**Comment by xeoshow** [comment]
Could you please kindly show a running demo for this? <sprite /> would be great! 
Just spent much time and still not get it working right ... 
Thank you v much !
