### ISSUE TITLE
Error when installing in nuxt

### ISSUE THREAD

**Issue by jewe** [hairyf/vue3-pixi#110]
In a fresh created Nuxt project i get the following error:
`Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.cache/vite/client/deps/vue3-pixi.js?v=d05e4a4e' does not provide an export named 'default' (at app.vue:1:148)`

Nuxt 3.11.2 with Nitro 2.9.6 

```
"vue3-pixi": "^0.9.1",
"vue3-pixi-nuxt": "^0.9.1"
```

**Comment by PumpkinPeasant** [comment]
same for me

**Comment by marcoshier** [comment]
same here
