### ISSUE TITLE
rename discussion

### ISSUE THREAD

**Issue by hairyf** [hairyf/vue3-pixi#117]
I want to come up with a suitable name, now that vue3 has been out for so long, it can't always be called vue3-pixi

so let's discuss it here

There are currently several suitable options:

**Comment by hairyf** [comment]
@vuepix/core (because @ vuepixi has already been registered)

**Comment by hairyf** [comment]
`@vue-pixi/core`

**Comment by mraeisbg** [comment]
To be honest, just call it whatever you think is cool. I don't think names are all that important. 
I'd choose something along the lines of your name, like:

pixiry.js - a Lightweight and flexible Vue 3 library for creating PixiJS applications.
airy.js - a Lightweight and flexible Vue 3 library for creating PixiJS applications.
or something. The slogan or description should be simple and fitting, but it already perfect, so it's all good.

By the way, it would be cool if you set up a Discord to talk about this kind of stuff with people in general. I'd like to join there and talk with others or ask a few questions or discuss best practices

**Comment by hairyf** [comment]
sure, thank you for your support, you are right

**Comment by hairyf** [comment]
You can now join the discussion at https://discord.gg/mRguTPnsB9. I will add it to the website later. I'm not very familiar with Discord, so feel free to give me any suggestions you may have.
