### ISSUE TITLE
对gl transition的支持

### ISSUE THREAD

**Issue by xeoshow** [hairyf/vue3-pixi#122]
看到另外一个开源：
https://awesome-image.vercel.app/zh/transition/introduction
https://awesome-image.vercel.app/zh/transition/gl-transition
https://codesandbox.io/p/sandbox/image-group-transition-b81gdl?from-embed=

pixi其实对gl的支持很强，是否可以类似上面开源里的AsTransition，vue3-pixi也增加相应的支持呢？这样vue3-pixi对Transition的支持就不仅仅局限于pixijs内置的那几个：
https://vue3-pixi.vercel.app/examples/filters-basic/blur.html

非常感谢。

**Comment by xeoshow** [comment]
这里还有个直接的示例，最下面的回复内容
https://github.com/pixijs/pixijs/issues/5552

**Comment by hairyf** [comment]
1. pixijs 内置是没有过渡的，Transition 组件是 vue3-pixi 携带的
2. 该功能比较小众，建议是看文档实现该扩展功能
