### ISSUE TITLE
 Failed to resolve vue3-pixi components

### ISSUE THREAD

**Issue by naonao-a** [hairyf/vue3-pixi#127]
"vite": "^4.3.2",
    "@vitejs/plugin-vue": "^4.1.0",
    "vue": "^3.2.47",

[Vue warn]: Failed to resolve component: sprite
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.

**Comment by hairyf** [comment]
https://vue3-pixi.vercel.app/guide/quick-start.html#initialize-vue-plugin
