### ISSUE TITLE
missing props in Application Component

### ISSUE THREAD

**Issue by evan-lc** [hairyf/vue3-pixi#41]
https://github.com/hairyf/vue3-pixi/blob/main/packages/vue3-pixi/src/components/application/index.ts
There is no `resizeTo` props declartion pass to `new _Application({ view: canvas.value, ...props })`

**Comment by hairyf** [comment]
I usually bind through the useElementSize of vueuse, like this:

```ts
import { useElementSize } from '@vueuse/core'

const { width, height } = useElementSize(myElement)
```

```html
<Application :width="width" :height="height">...</Application>
```

However, the Application component should support the resizeTo attribute, and I will fix it
