### ISSUE TITLE
could you include pixi-ui ?

### ISSUE THREAD

**Issue by DexYang** [hairyf/vue3-pixi#47]
i hope i can use to make ui....

**Comment by DexYang** [comment]
看了一会儿您的repo，说中文吧
![A76A3D8A](https://github.com/hairyf/vue3-pixi/assets/22140560/da1cdb5b-345c-40a6-93b9-b5a43f8d11cd)
我觉得UI用vue开发更直观点儿，可以把pixiui弄进来吗？

**Comment by hairyf** [comment]
它很好支持，我会添加一个 vue3-pixi-ui

**Comment by DexYang** [comment]
期待了

**Comment by DexYang** [comment]
请问有没有群或者论坛什么的

**Comment by hairyf** [comment]
> 请问有没有群或者论坛什么的

没有喔

**Comment by hairyf** [comment]
我发现 pixi-ui 发布在 3 年前，我认为这个功能不是必须，且过于老旧，在此关闭这个问题

**Comment by DexYang** [comment]
大佬你不做这个啦？

**Comment by DexYang** [comment]
是https://github.com/pixijs/ui  这个库，不是pixi-ui

**Comment by DexYang** [comment]
或者您能否指点一下我怎么做，我不知道怎么起手

**Comment by hairyf** [comment]
好吧，我看错了，我会实现它

**Comment by DexYang** [comment]
您好，请问您有QQ微信吗。。想请教一个问题

**Comment by hairyf** [comment]
你可以从我的个人博客中查找，不要在这里发表无关的提问

**Comment by DexYang** [comment]
是https://[hairy.blog](https://hairy.blog/)/吗？我打不开

**Comment by hairyf** [comment]
抱歉，我的域名过期了，你可以通过 https://hairy-blog.vercel.app/ 访问
