### ISSUE TITLE
(feature request) Component name prefix

### ISSUE THREAD

**Issue by leonardoraele** [hairyf/vue3-pixi#56]
Can we have a config option to add a prefix to the name of vue3-pixi vue components?

For example, instead of

```html
<Application>
    <sprite ... />
</Application>
```

I wish it could be:

```html
<PixiApp>
    <pixi-sprite ... />
</PixiApp>
```

**Motivation:** To distinguish pixi components from html tags and custom vue components.

**Comment by hairyf** [comment]
vue3-pixi naturally supports pixi prefix, custom prefixes are not currently supported, but you can still use  `<pixi-sprite>`

As for components such as Application and Loader, you can give them an alias.

```ts
import { Application as PixiApplication } from 'vue3-pixi'
```

```html
<pixi-application>
  <pixi-sprite ... />
</pixi-application>
```

**Comment by leonardoraele** [comment]
Good to know! Thanks
