### ISSUE TITLE
Nuxt3 Example

### ISSUE THREAD

**Issue by joe-mohan** [hairyf/vue3-pixi#59]
Any advice for adding this to a nuxt3 project?

**Comment by hairyf** [comment]
I will consider developing, please stay tuned

**Comment by 798714773** [comment]
waiting...

**Comment by matifanger** [comment]
bump

**Comment by duongxinh2003** [comment]
How long?

**Comment by hairyf** [comment]
In the [nuxt branch](https://github.com/hairyf/vue3-pixi/tree/nuxt), I don't have that much energy and am slowly developing

Welcome PR

**Comment by hairyf** [comment]
https://vue3-pixi.vercel.app/guide/nuxtjs.html
