### ISSUE TITLE
No PIXI Application found

### ISSUE THREAD

**Issue by chipslays** [hairyf/vue3-pixi#75]
Fresh Laravel project with InertiaJS.

I get the following error when trying to get a Pixi Application instance (or `useStage` and etc., but `onTick` works).

https://github.com/hairyf/vue3-pixi/blob/59a466f17bdfa4efc19b3fb7019c33c68da22609/packages/vue3-pixi/src/composables/useApplication.ts#L9

#### Code
```vue
<template>
    <div>
        <Application :width="240" :height="240">
            <text :anchor="0.5" :x="120" :y="120" :style="{ fill: 'white' }">
                Hello World
            </text>
        </Application>
    </div>
</template>

<script setup>
import { Application } from 'vue3-pixi';
import { useApplication } from "vue3-pixi";

const app = useApplication();
</script>
```

Without `const app = useApplication();` code works.

#### Env
```
"@inertiajs/vue3": "^1.0.0",
"vite": "^4.0.0",
"vue": "^3.2.41"
"pixi.js": "^7.3.2",
"vue3-pixi": "^0.8.4"
```

**Comment by hairyf** [comment]
Application injects instances through Vue injection, and you need to create components to obtain instances in `useApplication`

Additionally, you can achieve outermost use by manually creating pixi applications
