### ISSUE TITLE
gl.getInternalformatParameter is not a function.

### ISSUE THREAD

**Issue by helenhu0372** [hairyf/vue3-pixi#86]
gl.getInternalformatParameter is not a function. (In 'gl.getInternalformatParameter(gl.RENDERBUFFER, gl.RGBA8, gl.SAMPLES)',
When I use ios 12,13,14 safri, I got this error, is there any solution to fix it?

**Comment by hairyf** [comment]
Can you provide more information, such as the smallest use case that I will try to replicate in Safri? Thank you

**Comment by helenhu0372** [comment]
This is the js code(report.js)

import App from 'Project/vue_model/report.vue';
import 'Project/components/CommonUse.vue'
import { createApp } from 'vue'
import { Swipe, SwipeItem,Toast,setToastDefaultOptions } from 'vant';
import 'vant/es/toast/style';

const app = createApp(App)
app.use(Swipe);
app.use(SwipeItem);
app.use(Toast);
setToastDefaultOptions({ duration: 5000 });

app.mount('#app')



This is the vue code
import { Texture,TextMetrics,TextStyle as MyTextStyle } from 'pixi.js'
import { Application,Loader} from 'vue3-pixi'
import { onMounted, ref } from 'vue'

const wd = window
const dpr = window.devicePixelRatio
onMounted(()=>{
    setTimeout(() => {
        stageWidth.value = mainRef.value.offsetWidth
        stageHeight.value = mainRef.value.offsetHeight
})
}
<template>
    <div class="main" ref="mainRef" @touchstart="bodyClick">
        <Application ref="myCanvasSelect" id="myCanvasSelect" :resizeTo="wd" :height="stageHeight" :width="stageWidth" :backgroundAlpha="0" :resolution="dpr" :roundPixels="true">
            <pixi-Container>
                <text :x="stageWidth/2+4" :y="100" :anchor="0.5" :style="{fontSize: '16px',fill: '#FFFFFF'}">
                   test font .....
                </text>     
            </pixi-Container>
        </Application>
    </div>
</template>
            
            
            
![image](https://github.com/hairyf/vue3-pixi/assets/155242408/c5610323-c8b5-4d8d-9efb-0092653882fc)

I use webpack code

you can use this url to see the error
http://staging.intviu.cn:3003/activity/2023_report?access_token=token

**Comment by helenhu0372** [comment]
![image](https://github.com/hairyf/vue3-pixi/assets/155242408/e4c4e10a-8743-4de4-afe7-32d139f0afcf)
I test you demo project and got this error I have got before, so I use webpack to transform code to ES5, but I got the error gl.getInternalformatParameter is not a function. This error only show in ios under 15.

**Comment by hairyf** [comment]
It looks more like an error in pixijs, and I have found a corresponding solution
https://stackoverflow.com/questions/67726514/pixi-autodetectrenderer-typeerror-gl-getinternalformatparameter-is-not-a-functi
