### ISSUE TITLE
upgrade to vue3.4 gets Vue warn -> Failed to resolve vue3-pixi components

### ISSUE THREAD

**Issue by DexYang** [hairyf/vue3-pixi#90]
using [vue3-pixi-dino](https://github.com/hairyf/vue3-pixi-dino) 

Reproduction steps: 

1. upgrade vue to 3.4.3 and run dev server
2. press ctrl + s on vite.config.ts to restart vite server
3. gets Vue Warns in console:

- [Vue warn]: Failed to resolve component: Container
  If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
- [Vue warn]: Failed to resolve component: Text
  If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
- [Vue warn]: Failed to resolve component: Sprite
  If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.

**Comment by hairyf** [comment]
Upgrading vite, @ vitejs/plugin vue, and vue simultaneously did not result in such an error
